<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-deviceAgent-8a282907-fbf4-4176-aeb0-ca1fb6fb90ce</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Evolis.SDK" Version="9.4.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.29" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="PCSC" Version="7.0.1" />
    <PackageReference Include="PCSC.Iso7816" Version="7.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    <ProtoBuf Include="proto\deviceAgent.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="pattern\" />
  </ItemGroup>
</Project>
